### ISSUE TITLE
Differentiate between substantive and editorial

### ISSUE THREAD

**Issue by plehegar** [w3c/display_errata#1]
It would be good to differentiate between the 2 cases since the W3C Process is using 2 different update path for each case. This would allow us to quickly conclude which path to take when looking at doing an update.

**Comment by iherman** [comment]
@plehegar I have made a new version; see the test example at:

https://w3c.github.io/display_errata/test.html

Is this what you asked for?

**Comment by plehegar** [comment]
yep. this looks good to me. I like the fact that issues are by default substantive unless said otherwise.
