### ISSUE TITLE
Closed issues should be listed

### ISSUE THREAD

**Issue by plehegar** [w3c/display_errata#12]
[WebCrypto issues list](https://github.com/w3c/webcrypto/labels/Errata) contains open and closed issues with the label `Errata`. Yet only the open ones are listed in the [errata page](https://w3c.github.io/webcrypto/errata.html). I close issues once the change is made in the editor's draft but the REC doesn't contain those yet. Thus they should be listed.

cc @himorin

**Comment by iherman** [comment]
@plehegar it should work now. In 

https://w3c.github.io/webcrypto/errata

all issues (including pull requests labeled as errata) are listed. The state is flagged to make it clear which ones are open, and there is also a note for each issue on whether it is a pull request or 'just' an issue.

I hope that is what was expected:-)

**Comment by plehegar** [comment]
Perfect! Thank you Ivan.
