### ISSUE TITLE
typo in SPARQL 1.1 Query Language

### ISSUE THREAD

**Issue by debugger-zhang** [w3c/display_errata#18]
https://www.w3.org/TR/sparql11-query/

"The syntax error arises for use of a variable as the named target of AS (e.g. ... AS ?x) when the variable is used inside the WHERE clause of the SELECT or if already used as the traget of AS in this SELECT expression"

“traget" should be "target"

**Comment by iherman** [comment]
@debugger-zhang, sorry about the _very_ late reaction, but I do not actively maintain this repository any more (although the tool itself is still used). But this repository is not meant to collect errata for specific documents; this should follow the conventions set up by the specific recommendation (see https://www.w3.org/2013/sparql-errata#sparql11-query for this specific case).

I will close this issue, but also cc this to the editor of the document itself.

Cc: @afs @pchampin

**Comment by afs** [comment]
Errata applied to SPARQL 1.2
