### ISSUE TITLE
Updated ED draft that reflects the errata?

### ISSUE THREAD

**Issue by plehegar** [w3c/display_errata#2]
The workflow is silent on edits. It would be good if we can recommend some Git branch jitsu in order to always have an ED copy of the spec with all errata folded in. For example, we could recommend that a specific branch be created for that purpose.

**Comment by plehegar** [comment]
Agreed, but since your README.me includes the workflow, it would be good to include the thinking around ED as part of it. I could send a pull request if it helps.

**Comment by iherman** [comment]
Yes please. A PR would be great.
