### ISSUE TITLE
test-driven for substantive errata

### ISSUE THREAD

**Issue by plehegar** [w3c/display_errata#3]
Since the Process requires implementation experience for substantive errata, we should add "ALL substantive corrections are generally expected to have corresponding test(s) (such as a pull request in web-platforms-tests), either in the form of new tests or  modifications to existing tests, or must include the rationale for why test updates are not required for the proposed update."

**Comment by iherman** [comment]
Do you mean that this text should be added to the cover HTML file? Maybe that should be done only if #1 is handled (which need some coding...).

**Comment by plehegar** [comment]
The text should be added in thee README.me. Want me to do a pull request?

**Comment by iherman** [comment]
Yes please.
